##############################################################
##############################################################
# This particular config is for comparing a live version of
# of ie.panavision.com with a historical baseline of the site.
#
# To run:  `wraith latest panavision-ie`
#
##############################################################
##############################################################
# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
#browser: "casperjs"
browser: "phantomjs"

# (required) The domains to take screenshots of.
domains:
  live:  "http://ie.panavision.com"

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  home-ie:  /
  digital-ie:  /ie/products/cameras/digital
  film-ie:  /ie/products/cameras/film
  anamorphic-ie:  /ie/products/optics/anamorphic
  spherical-ie:  /ie/products/optics/spherical
  large-format-ie:  /ie/products/optics/large-format
  remote-ie: /ie/products/remote-systems
  grip-ie:  /ie/products/grip
  worldwide-locations-ie:  /ie/worldwide-locations
  euope-ie:  /ie/europe
  north-america-ie:  /ie/north-america
  product-ie:  /products/ie/anamorphic-zooms

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
# If you don't specify height it will default to 1500px 
screen_widths:
  - 320x3200
#  - 600x768
  - 768x3220
  - 1024x5440
  - 1280x5000

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
#before_capture: 'javascript/disable_javascript--phantom.js'
before_capture: 'javascript/wait--phantom.js'
#before_capture:  'javascript/wait--casper.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots/panavison-ie'
history_dir: 'historical-baselines/panavision-ie-history'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 400

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
